- core/api.cfc
- core/factory.cfc
- dashboard/dashboard.cfm
- tests/resources/ConflictingURI.cfc
- tests/resources/EchoURIAlias.cfc
- tests/tests/TestConflict.cfc
- tests/tests/TestCore.cfc
- tests/tests/TestFactory.cfc
Added the ability to specify a comma delimited list of URIs for taffy_uri, allowing you to specify multiple endpoint URIs to be served by the same resource .  It will not recognize commas inside of regular expression brackets {}.
Fixed an issue where status.skippedResources was being overwritten when hot-swapping.
Added tests for the new alias', as well as reconfiguring the tests to keep testing the skippedResources properly.
Added a test for conflicting URI errors.
> https://github.com/atuttle/Taffy/issues/239

- dashboard/dashboard.cfm
Now that the allowCrossDomain setting can be a regular string, the framework config modal dialog on the dashboard needed to be updated to properly handle non-boolean values
> Fixed regression from #251

- core/api.cfc
- dashboard/dashboard.cfm
- tests/resources/uriAliasDoesntBeginWithForwardSlash.cfc
- tests/resources/uriDoesntBeginWithForwardSlash.cfc
- tests/tests/TestConflict.cfc
- tests/tests/TestCore.cfc
- tests/tests/base.cfc
Added exception thrown when uri or uri alias is not starting with a forward slash, and added the tests accordingly. Changed the Dashboard to show this new error.
> resolves #253

- core/api.cfc
@atuttle - I'm not sure about the server-level check, but given that this is only done when Taffy is initialized, it seems like this is an adequate fix. I tested application-level mappings, server-level mappings and the existing "guess" method in ACF11.
The ServiceFactory class is documented in Railo (http://www.getrailo.org/javadoc-4-0/coldfusion/server/RuntimeService.html), so I'm assuming it should work there as well.
> added checks for app and server-level mappings

- dashboard/dashboard.cfm
Removed potentially invalid characters from html div id to allow the test form to be used when the bean name contains unusual characters.
The bean names for services in my application were named after their rest path. IE:
```
<bean id="/example/status" class="com.foo.bar.rest.example.status" />
```
The front slashes in the bean name were causing the a tag and the associated div tags to use invalid ids/names. I used a regex to reduce the generated ID to only use alphanumeric characters and underscore. This resolved the problem.
> Removed potentially invalid characters from html div id

- core/api.cfc
- core/factory.cfc
I've opted for passing the external beanfactory into Taffy's factory, and let getBean() ultimately check the external factory for the bean. If you have any remarks about the changes, please let me know.
> Issue 277 recursively resolving dependencies

- core/api.cfc
Replaced coldfusion.server.ServiceFactory.getRuntimeService.getMappings() with directoryExists() as the ServiceFactory class is not implemented in Railo and Lucee.
> Modify check for /resources mapping to support Railo/Lucee

- core/resource.cfc
I'm starting to use Taffy on a Lucee server for a project and ran into an error with QueryToStruct and noticed that there is no check for the Lucee server in that method. I
> Add Lucee support to QueryToStruct

- core/api.cfc
If Taffy should not handle this request, do not call it's onApplicationStart() even if reloadEveryRequest is true or the URL keys match
> Stop Taffy intercepting requests in ignored folders when applicaton starting up

- core/api.cfc
The onTaffyRequestEnd function  is really useful for separating resources and logging request/response. Avoiding duplication of code to log endpoint response.
In this change we returned status code to onTaffyRequestEnd for us to capture the status code returned by the resources.
> Adding Status code onTaffyRequestEnd

- examples/api_uploadImg/resources/imageCollection.cfc
Setting destination to `getTempDirectory()` by default instead of expandPath under the web root.
> Example Upload destination getTempDirectory()

- dashboard/dash.js
When entering a qparam value for a resource in the dashboard, strings are not properly encoded in the resourceURI fields. During the queryparam creation, the values are correct, but they are then decoded before being placed in the URI field. This will cause key values like this:
`/resource?apikey=eN+W/tydEqyG6VhsLzBoOqCmIlFg7PB5MIoKFmZiw6k=`
To *not* be escaped, and they are no longer value URLs. Removing the decodeuri function will instead put the following into the URI field:
`/resource?apikey=eN%2BW%2FtydEqyG6VhsLzBoOqCmIlFg7PB5MIoKFmZiw6k%3D`
> Update dash.js to properly URI encode URLs

- dashboard/docs.cfm
On initial load, clicking the heading for a resource will attempt to expand the panel, when it is already expanded. A second click will then collapse the panel, and behavior will return to normal.
Added `class="in"` to the resource section of each panel so that the initial click on a heading will properly collapse the panel.
This could probably use a bit more work to ensure that the group behavior is polished.
> Update docs.cfm to correct bad collapse behavior

- core/api.cfc
I realize this is for a very old version of CF, but the latest Taffy 3.1.0 won't run out of the box on CF8 (our current version) as it doesn't support the ternary operator. This change resolves that at the expense of using IIf() which may have performance impacts, etc. Perhaps this has been addressed in some other way (an alternate version of Taffy?), but for people stuck on CF8, this may be helpful, since the latest Taffy claims CF8 compatibility.
Additionally, StructNew() is used here as {} throws a "Missing argument name. When using named parameters to a function, every parameter must have a name." error.
Server Product  ColdFusion
Version     8,0,1,195765  
Edition     Developer  
Serial Number   Developer  
Operating System    UNIX  
OS Version  3.0.101-0.7.17-default  
JVM Details …
> CF8 Ternary Operator Compatibility in api.cfc

- core/baseSerializer.cfc
- tests/tests/TestRepresentations.cfc
If no `statusText` is passed into `withStatus()`, then lookup what the "standard" status text would be based on the (required) `statusCode`. The list of codes and texts were pulled from https://httpstatuses.com/
P.S. Taking a cue from `variables.types` on how to setup the struct/map on the serializer. A test was also added for this functionality.
This would resolve #329
> `withStatus()` lookup `statusText` based on `statusCode`

- dashboard/dash.js
If a jsonapi ([jsonapi.org](http://jsonapi.org)) content type (application/vnd.api+json) is specified as the taffy_mime in the serializer then the json is now correctly formatted in the dashboard output.
> Add support for jsonapi in dashboard response json

- dashboard/docs.cfm
Hiding can be done on the resource, the method/verb, or individual method parameters.
Hiding is done to the customer facing docs only, and not the developer dashboard.
Signed-off-by: Jeff Kiah <y2kiah@hotmail.com>
> Added ability to hide from docs using "taffy_docs_hide" or "taffy:docs:hide" attribute.

- core/baseDeserializer.cfc
Handle case where a parameter may be passed more than once.
On Adobe ColdFusion a request sent with `application/x-www-form-urlencoded` gives a body such as:
'foo=1%2C2%2C3&foo=20&foo=30'
For a POST request you get:
"foo":"1,2,3,20,30"
For PUT / PATCH / DELETE requests you get:
"foo":30"
Tested on ACF 2016. Also tested on Lucee 5 which is not affected by the above issue (as Lucee populates the form scope for PUT / PATCH / DELETE requests), and does not break with this proposed patch.
Example cURL requests:
curl --request PATCH \
--url 'http://127.0.0.1:43998/taffy/examples/api/index.cfm?endpoint=%2Fping' \
--header 'cache-control: no-cache' \
--header 'content-type: application/x-www-form-urlencoded' \
--header 'postman-token: 7cb10378-8079-356b-9ae7-54677e308a21' \
--data …
> Handle case where a parameter may be passed more than once.

- core/api.cfc
Fix for **variable [DATA] does not exist on line 12** within core.nativeJsonDeserializer when attempting to process a request with http body == null and Content-Type == application/json
See https://trycf.com/editor/gist/cc470e44e847c08f2bc455cd3914a7ee/lucee5?theme=monokai for reproduction.
Bug experienced within Lucee 5.2.4.35-RC on Java 1.8.0_144, with the following http request:
`DELETE /company/23605856-B653-4492-90A4-90C942896B1A HTTP/1.1
Authorization: ***** Hidden credentials *****
Content-Type: application/json
Host: ***** Hidden host *****
Connection: close
User-Agent: Paw/3.1.4 (Macintosh; OS X/10.11.6) GCDHTTPRequest
Content-Length: 4
null`
Same application did not exhibit this behaviour when running on Adobe CF 9.0.1 on Java 1.6.0_24, although this was with an earlier version …
> Fix for http body containing null

- dashboard/dashboard.cfm
- dashboard/docs.cfm
Resolves #316
Resolves #288
It seems that as of CF11 the script component syntax doesn't like component metadata with two colons, like `taffy:docs:hide` or `taffy:dashboard:name`... sigh. (This syntax does work in tag components, but why on earth would you want to write those??) This is why we can't have nice things, Adobe.
So continuing the tradition of ugliness:
- `taffy:docs:hide` ~= `taffy_docs_hide`
- `taffy:docs:name="foo"` ~= `taffy_docs_name="foo"`
- `taffy:dashboard:name="bar"` ~= `taffy_dashboard_name="bar"`
- `taffy:dashboard:hide` ~= `taffy_dashboard_hide`
When displaying in the dashboard, if `taffy:dashboard:name` is not defined but `taffy:docs:name` is, the latter will be used as the display name. In the documentation, `taffy:dashboard:name` is never checked. In both …
> Allow renaming and hiding of resources in dashboard/docs

- bonus/LogToBugLogHQ.cfc
I'm a first-timer and I think this is what you want?
Just adding a var to that line.
> The required var has been added.

- core/api.cfc
- core/factory.cfc
- local variables( var scope) should be declared /defined before other variables are initialized.
- There seems to be an issue with optional arguments for a function inside cfscript, so changed that to tag based code to make it working on CF8.
> Fixed some CF8 compatibility issues

- core/api.cfc
- dashboard/dashboard.cfm
Some Frontend Frameworks use some automatic CSRF logic (e.g. Angular is looking for a cookie named XSRF-TOKEN and automatically add it to the request header as X-XSRF-TOKEN). If this check is added to onTaffyRequest() the dashboard would require to add this value manually for each request.
This PR is adding new settings to name the cookie and the header and if both filled the dashboard will process it.
> add csrf token logic

- bonus/LogToLog.cfc
adds a simple exception log adapter which is using cflog
config:
```
exceptionLogAdapter = "taffy.bonus.LogToLog",
exceptionLogAdapterConfig = {
logfile = "taffy"
}
```
> LogToLog Exception Logging Adapter

- dashboard/dashboard.cfm
In the dashboard, check for `TAFFY_DOCS_HIDE` metadata on the resource argument. 
If it exists, do not include the argument in the constructed JSON or the dashboard docs sidebar.
Was going to use `<cfcontinue>` instead of nesting in a `<cfif>` but `<cfcontinue>` is CF9+ and I believe Taffy supports CF8+.
**Reason for requested change.**
I have arguments passed into my resource that are added in the `onTaffyRequest` method, so do not want them passed by the API caller. An example of this is to add a `User` argument parameter which is based on a header authentication token, so instead of looking it up in each resource, then I do it in `onTaffyRequest`. Not sure if that is a valid use case but seems to work well.
> exclude params flagged with TAFFY_DOCS_HIDE

- core/api.cfc
- core/baseSerializer.cfc
- core/resource.cfc
- added a noContent() function that enhance the noData() one by sending back 204 HTTP Status and text/plain Content-Type to avoid misinterpretation of empty json content
- added noDataSends204NoContent framework setting to force noData to behave like noContent
>  noData() sends invalid response #365

- .travis.yml
- box.json
There was an issue in commandbox that prevented the recipe from finishing when the box.json contains a command as a dependency (which this one does, cfconfig) causing the commandbox shell to reload, and it forgets to do the third step of the recipe (start the server). 
I switched to using `cfmatrix/install.sh` which can check to see if the server started and try to start it again.
> Fixed the Travis-CI Build

- box.json
Filled out `box.json` to improve the experience when using the repository as a dependency endpoint with CommandBox. This could also be used to publish to ForgeBox if the interest arises (and ownership is transferred).
* Ignores files that are unnecessary for deployment
* Lowercased slug so that default installation folder matches docs
* Other changes that would really only matter for ForgeBox
* Formatting
> Filled out box.json

- core/api.cfc
- dashboard/dashboard.cfm
* move URI to left column for easier visual identification
* move cfc name to content panel
* ensure URI sorting is case-insensitive
> dashboard cleanup

- core/api.cfc
Resolves #366 
If a resource returns anything other than a representation instance, wrap it in an instance for the user
Full credit for the idea goes to @y2kiah -- I was only going to have it throw a more useful error message, but why not do the developer a favor?
> Allow bare return from resources

- dashboard/dashboard.cfm
- Fixed the help doc links in the Taffy Dashboard's Framework Configuration to use new URL format.
- I don't find it good practice to have help links (or most any external links) navigate away from your application, so they now always open in a new tab/window.
> Fix doc links in Dashboard

- bonus/LogToBugLogHQ.cfc
Back in #327 we added `addDebugData()` and it adds contextual data for text and email logs. This extends that to also be included for BugLogHQ.﻿
> Add debug data to BugLogHQ exception logs

- core/baseSerializer.cfc
Replacing a colon with an equals sign in a struct definition to correct a bug that will only show up in CF versions less than 10. This is the root cause for issue #389.
> Replace colon with equals sign for older CF support

- core/api.cfc
> Work around for Cannot invoke "java.lang.Class.isPrimitive()"

- box.json
- core/api.cfc
- docs/@next.md
- package.json
- tests/Application.cfc
This PR add support for a new `exposeTaffyHeaders` setting, which is `true` by default to preserve backwards compatibility.
When set to `false`, it will prevent the following headers from being sent in the HTTP response:
* `X-TAFFY-RELOADED` 
* `X-TIME-TO-RELOAD`
* `X-TIME-IN-PARSE`
* `X-TIME-IN-ONTAFFYREQUEST`
* `X-TIME-IN-RESOURCE`
* `X-TIME-IN-CACHE-CHECK` 
* `X-TIME-IN-CACHE-GET`
* `X-TIME-IN-CACHE-SAVE`
* `X-TIME-IN-SERIALIZE`
* `X-TIME-IN-TAFFY`
* `X-TIME-IN-ONTAFFYREQUESTEND`
I also updated the documentation to document what each of these headers means (at least based on my understanding).
My intention was to include unit tests for this, but I was running into tons of issues trying to get the unit tests running in Commandbox. The documentation here seems be very outdated.
> Added new exposeTaffyHeaders

- box.json
- core/api.cfc
- docs/@next.md
- package.json
- tests/Application.cfc
Added new resourcesCFCPath setting which allows you to configure the "resources" components path in cases where the "resource" folder may conflict with existing directory structures. The default behavior is unchanged (for backwards compatibility), you would only need to set this when the `/resources` folder conflicts with your existing application or you just want to use your own directory structure.
For example, instead of using the `resources` convention you could place your resources in a completely different directory using:
```
variables.framework.resourcesCFCPath = "private.api.components"
```
This would expect all your Taffy "resources" would live in the physical folder of `expandPath('/private/api/components')` and that your components can be creating using the dotted path prefix …
> Add support for new resourcesCFCPath setting
